name: Deploy to GitHub

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IS_GITHUB: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          [ -e public ] && rm -r public
          yarn install
          yarn build
          echo eliasbobadilla.com >> public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
